feat: добавить функционал бронирования, отзывов
AlbinaKuznetsova/java-shareit pull request #2
Opened 2024-05-15 21:07 UTC by AlbinaKuznetsova

2024-05-16 15:34 UTC, andrew-larkin requested changes
Привет! Очень хорошо, качественная реализация, остается местаим внести небольшие правки и можем двигаться дальше.

2024-05-16 15:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto,
в ответах контроллера всегда возвращаем dto а не сущность

2024-05-16 15:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private Item item;
в dto используем либо id сущности, либо другие dto

2024-05-16 15:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryOld.java
> +public class ItemRepositoryOld {
это мы можем удалить

2024-05-16 15:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
использовать чужие репозитории в сервисах - плохая практика. можно внедрять один сервис в другой

2024-05-16 15:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserRepositoryOld.java
> +public class UserRepositoryOld {
удаляем

2024-05-17 06:52 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryOld.java
> +public class ItemRepositoryOld {
Удалила

2024-05-17 06:52 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/user/UserRepositoryOld.java
> +public class UserRepositoryOld {
Удалила

2024-05-17 06:53 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private Item item;
Оставила id

2024-05-17 07:28 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
Исправила, но получилась циклическая зависимость. Разрешила ее с помощью аннотации Lazy, но правильно ли это?

2024-05-17 07:46 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto,
Исправила

2024-05-23 19:16 UTC, merged