feat: requests
AlbinaKuznetsova/java-shareit pull request #3
Opened 2024-05-31 16:53 UTC by AlbinaKuznetsova

добавить запрос вещи, пагинацию, реализовать тесты на весь функционал

2024-05-31 22:45 UTC, andrew-larkin requested changes
Привет! Отличная работа, реализация нового функционала довольно качественная, но местами нужно внести небольшие правки и сможем двигаться дальше.

2024-05-31 22:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
на строке 58 Booking стоит поместить в Optional

2024-05-31 22:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Integer requestId;
тут добавляем связь с ItemRequest

2024-05-31 22:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoOut.java
> +    private User requestor;
в dto нельзя использовать модели-сущности, только другие dto или id

2024-05-31 22:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoOut.java
> +@Component
dto не является компонентом

2024-05-31 22:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoIn.java
> +@Component
не является компонентом. нужно проверить чтобы в других dto такого не было

2024-06-01 14:59 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoIn.java
> +@Component
Исправлено

2024-06-01 14:59 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoOut.java
> +@Component
Исправила

2024-06-01 14:59 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoOut.java
> +    private User requestor;
Исправила

2024-06-01 15:02 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
исправлено

2024-06-01 19:45 UTC, AlbinaKuznetsova commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Integer requestId;
Исправила

2024-06-08 15:24 UTC, merged